### ISSUE TITLE
Valid license missing

### ISSUE THREAD

**Issue by spacetime** [finn-no/guava-metrics#3]
This project does not have a license, could you add one?

**Comment by spacetime** [comment]
I guess I'll reopen this one instead of creating a new one. The license doesn't have any authors, could that be fixed?

**Comment by Andersos** [comment]
You are referring to this line right? https://github.com/finn-no/guava-metrics/blob/master/LICENSE#L189

**Comment by spacetime** [comment]
Yes

**Comment by hennings** [comment]
Thanks for notifying! Updated the LICENSE.
